# Generated by Django 4.2.6 on 2024-06-10 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("os", models.CharField(max_length=100)),
                ("browser", models.CharField(max_length=100)),
                ("device", models.CharField(max_length=100)),
                ("day", models.DateField(auto_now_add=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Visits",
                "ordering": ["-date"],
                "unique_together": {("ip_address", "day")},
            },
        ),
        migrations.CreateModel(
            name="VisitHits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hits", models.IntegerField(default=0)),
                (
                    "visit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visit_hits",
                        to="visits.visit",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Visit Hits",
                "ordering": ["-hits"],
            },
        ),
    ]
