version: '3.7'

services:
  postgres:
    image: "postgres:11"
    container_name: ${SQL_HOST}
    env_file:
      - .env
    volumes:
      - ~/my_website/my_django_website/postgres_data:/var/lib/postgresql/data/
    networks:
      - my_website
  web:
    image: ${AMAZON_IMAGE}
    command: gunicorn --workers=3 core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
      - 3010:3010
    volumes:
      - ~/my_website/my_django_website/static:/usr/src/app/static
      - ~/my_website/my_django_website/media:/usr/src/app/media
    env_file: .env
    # env_file: ./backend/.env
    # environment:
    #   - DEBUG=1
    #   - SECRET_KEY=foo
    #   - SQL_ENGINE=django.db.backends.postgresql
    #   - SQL_DATABASE=postgres
    #   - SQL_USER=postgres
    #   - SQL_PASSWORD=postgres
    #   - SQL_HOST=host.docker.internal
    #   - SQL_PORT=5800
    #   - DATABASE=potgres
    #   - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
    #   - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    #   - REDIS_HOST=redis
    #   - RUNMAIN=1
    # depends_on:
    #   - db
    depends_on:
      - postgres
    networks:
      - my_website

volumes:
  postgres_data:


networks:
  my_website:
