version: '3.7'

services:
  db:
    image: "postgres:11"
    container_name: "postgres"
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5800:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
  web:
    image: "ahmedsaied94/saied_back_image:latest"
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
      - 3000:3000
    volumes:
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    # env_file: .env
    # env_file: ./backend/.env
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=host.docker.internal
      - SQL_PORT=5800
      - DATABASE=potgres
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - REDIS_HOST=redis
      - RUNMAIN=1
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:


networks:
  main:
