# Generated by Django 4.2.4 on 2023-08-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mywebsite", "0002_alter_project_main_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="live_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
