# Generated by Django 4.2.4 on 2023-08-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mywebsite", "0003_project_github_link_project_live_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
