# Generated by Django 4.2.4 on 2023-08-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mywebsite", "0004_image_description_image_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="github_link",
            new_name="github_back_link",
        ),
        migrations.AddField(
            model_name="project",
            name="github_front_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
