# Generated by Django 4.2.6 on 2024-06-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mywebsite", "0005_rename_github_link_project_github_back_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
