version: '3.7'

services:
  nginx:
    image: "nginx:latest"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/mywebsite/my_django_website/nginx:/etc/nginx
      # - -v /var/www/html:/var/www/html
      # extra_hosts:
      #   - "docker.host:host-gateway"

networks:
  main:
