version: '3.7'

services:
  nginx:
    image: "nginx:latest"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/my_website/my_django_website/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ~/my_website/static:/home/ubuntu/my_website/static
      - ~/my_website/media:/home/ubuntu/my_website/media
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      # - -v /var/www/html:/var/www/html
      # extra_hosts:
      #   - "docker.host:host-gateway"
    network_mode: "host"
networks:
  main:
